### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [am-willmore/Codecademy#1]
**Pandas and CSV (4/4)**
The file imports the necessary libraries and converts the CSV to a Pandas DataFrame. 

**Implementation of visualizations in spec. (4/4)**
The file renders all Seaborn and Matplotlib visualizations and content provided in the design specification.

**Color (2/4)**
Color is standard and does not carry meaning. Visualizations don't different palettes with purpose. 

**Style (4/4)**
The chart labels and titles are concise, easy to read, and some titles are framed as questions.

**Presentation and Framing of Visualizations (4/4)**
Presentation cohesively presents every chart and has an appropriate description for each, with further research outlined in the notes.

---

Excellent job! I especially thought your presentation was well done. I'd only recommend adding more creativity to your visuals, especially in terms of color and having that color fit your topic.

**Comment by am-willmore** [comment]
Thanks for your feedback!
