### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zjedwin** [am-willmore/Codecademy#2]
1. Include an initial slide stating an objective for your presentation to help the reader contextualize the information they're seeing.
2. It would be helpful to provide a short description for each of the pages for the site explaining their significance.
3. Providing a definition of 'first' and 'last' touch in the context of this assignment would be valuable.
4. The description of the user's journey has too few details.
5. The optimization strategy needs more careful explanation.

**Comment by am-willmore** [comment]
Thanks for your feedback!
